### ISSUE TITLE
Running LmcpGen on OpenUxAS MDMs results in an error

### ISSUE THREAD

**Issue by sahabi** [afrl-rq/LmcpGen#10]
I kept getting an error when I run ./RunLmcpGen.sh in OpenUxAS:

Error: (Line 21) Attribute "Optional" must be declared for element type "Field".
Error: (Line 23) Attribute "MaxArrayLength" must be declared for element type "Field".

Fixed it by adding the bolded last two lines in MDM.DTD.
!ATTLIST Field
    Default CDATA ''
    Type CDATA #REQUIRED
    Name CDATA #REQUIRED
    Series CDATA ''
    Units CDATA 'None'
    LargeArray CDATA ''
    **MaxArrayLength CDATA ''
    Optional CDATA** ''
  

Let me know if this fix is OK and I'll push the changes.

**Comment by derekkingston** [comment]
That should be in the latest develop branch now. I'll make a new release that incorporates this change.
